const hjError = {
  not_null               : '不能为空',
  mobile_illegal         : '手机号码不合法',
  match_input            : '必须于上一次的输入相同',
  same_username_pwd      : '用户名和密码不能相同',
  start_with_error_sign  : '不能以下划线或数字开头',
  username_illegal       : '用户名为4-20个不含特殊符号的字符',
  sms_illegal            : '短信码格式不正确',
  pwd_illegal_letter     : '密码不能使用纯数字或纯字母',
  pwd_illegal_length     : '密码长度为8-20位',
  pwd_empty              : '密码不能为空!',
  username_empty         : '用户名不能为空!',
  mobile_empty           : '手机号码不能为空!',
  email_empty            : '邮箱不能为空!',
  sms_empty              : '动态码不能为空！',
  captcha_empty          : '验证码不能为空!',
  match_username_pwd     : '用户名密码不匹配',
  mobile_exist           : '该手机号已注册',
  captcha_wrong          : '图片验证码输入错误',
  email_exist            : 'email已存在',
  sms_wrong              : '动态码输入错误',
  username_sensitive     : '用户名不可以包含敏感词哦',
  username_exist         : '用户名与其他沪江帐号重名',
  email_unregister       : 'email未注册',
  mobile_unregister      : '手机未注册',
  no_network             : '无网络链接',
  account_frozen         : '帐号被冻结',
  username_inexist       : '用户名不存在',
  username_blocked       : '用户帐号被锁定',
  username_unallowed     : '用户名不符合规则',
  third_binded           : '第三方帐号已绑定其它沪江帐号',
  third_unlogin          : '第三方帐号未登录',
  sms_exceed_times       : '动态码错误次数过多，请重新获取',
  pwd_find_invalid       : '找回密码第一步未通过验证',
  sms_repeat_fetch       : '60秒内不能重复发送短信',
  match_pwd              : '两次密码输入不一致',
  sys_err                : '系统错误',
  no_login               : '沪江帐号未登录',
  data_null              : '返回数据记录为空',
  para_error             : '参数错误',
  request_err            : '请求方式错误',
  action_deny            : '用户已登录，action不允许被调用',
  interest_exist         : '用户兴趣已存在，更新兴趣失败',
  has_bound              : '沪江帐号已与其它第三方帐号绑定',
  bind_fail              : '第三方帐号绑定沪江帐号操作失败',
  third_register_fail    : '第三方帐号注册沪江帐号失败',
  sign_up_fail           : '注册失败',
  has_modify_username    : '已修改过用户名，无法再修改',
  username_reach_limit   : '已达到修改用户名次数上限',
  username_is_used       : '新用户名重复',
  username_same_old      : '原用户名与新用户名一致',
  change_username_overdue: '修改用户名过期',
  spec_username_unexisted: '指定的用户不存在',
  username_null          : '用户名为空',
  pwd_null               : '密码为空',
  pwd_invalid            : '密码不符合规范',
  pwd_twice_diff         : '二次密码不匹配',
  pwd_wrong              : '密码不正确',
  interest_null          : '领域不能为空',
  format_err             : '数据格式错误',
  black_ip               : '当前Ip在黑名单中，拒绝注册操作',
  sms_exceed_limit       : '当日手机发送短信次数超限',
  sms_send_fail          : '发送失败',
  email_redirect_err     : '邮件链接回跳地址 参数异常',
  third_not_bind         : '第三方帐号未绑定沪江帐号',
  email_invalid          : 'email链接失效',
  third_info_fail        : '第三方信息获取失败',
  only_app_call          : '不是app 不能调用',
  anonymous_info_fail    : '匿名用户转正式 调用hjapi accesstoken获取用户失败',
  anonymous_trans_fail   : '匿名用户转正式用户 失败',
  invalid_token          : '无效Token',
  exceed_call_limit      : '超出调用次数限制',
  request_timeout        : '请求超时',
  too_busy               : '操作过于频繁，请稍后再试'
}

export default hjError
